### ISSUE TITLE
Vector2 Dot-Product incorrect

### ISSUE THREAD

**Issue by fnawratil** [engeniousproject/engenious#1]
https://github.com/engeniousproject/engenious/blob/238291d43fd30b93e277c3014ec02960e58e0bd8/Math/Vector2.cs#L235

Incorrect calculation of vector2 dot-product.
Addition currently: value1.x + value2.y
Should be: value1.x + value1.y

**Comment by jvbsl** [comment]
fixed by https://github.com/engeniousproject/engenious/commit/353085c88db9fbea359191327bcda1b1d79a04f5
