### ISSUE TITLE
SpriteBatch should restore index and vertex buffer on flush

### ISSUE THREAD

**Issue by TheBlubb14** [engeniousproject/engenious#25]
The issues is that we just set both buffers to `null` instead of restoring them
See 
https://github.com/engeniousproject/engenious/blob/b38a93c81f790d43bb79d6ad95cd4f20dc2d0055/Graphics/SpriteBatcher.cs#L206-L207

**Comment by jvbsl** [comment]
Should be fixed https://github.com/engeniousproject/engenious/commit/478c042f335e7d590797acf3dcb028d8a278ecc7
